apiVersion: v1
kind: Deployment
metadata:
  name: appdeployment
  labels:
    app: appv1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semilla
  template:
    metadata:
      labels:
        app: appv1
    spec:
      containers:
      - name: appv1
        image: berluseden/demojenkins:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: appv1
  annotations:
    
  labels:
    app: appv1
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: appv1
  sessionAffinity: None
